/* 
 * @desription: File for string literal constants for messages in the fitness app
 *  This file is for notification messages, status_for, and status_type
 */

//status for
const NOTIF_FOR_CUST = 'CUSTOMER';
const NOTIF_FOR_COACH = 'COACH';

//notify type
const NOTIF_TYPE_FOCUS_SESSION_OPENED = "FOCUS_SESSION_OPENED";
const NOTIF_TYPE_FOCUS_SESSION_COMPLETED = "FOCUS_SESSION_COMPLETED";
const NOTIF_TYPE_FOCUS_SESSION_FEEDBACK = "FOCUS_SESSION_FEEDBACK";
const NOTIF_TYPE_FOCUS_SESSION_APPROACH = "FOCUS_SESSION_APPROACH";

//notif messages
const NOTIF_MSG_FOCUS_SESSION_OPENED = "Your coach has opened a new focus session for you.";
const NOTIF_MSG_FOCUS_SESSION_COMPLETED = " has completed a focus session.";
const NOTIF_MSG_FOCUS_SESSION_FEEDBACK = "You have new focus session feedback waiting for you!";
const NOTIF_MSG_FOCUS_SESSION_APPROACH = "One of your clients has an upcoming focus session.";


module.exports.NOTIF_FOR_CUST = NOTIF_FOR_CUST;
module.exports.NOTIF_FOR_COACH = NOTIF_FOR_COACH;
module.exports.NOTIF_TYPE_FOCUS_SESSION_OPENED = NOTIF_TYPE_FOCUS_SESSION_OPENED;
module.exports.NOTIF_TYPE_FOCUS_SESSION_COMPLETED = NOTIF_TYPE_FOCUS_SESSION_COMPLETED;
module.exports.NOTIF_TYPE_FOCUS_SESSION_FEEDBACK = NOTIF_TYPE_FOCUS_SESSION_FEEDBACK;
module.exports.NOTIF_MSG_FOCUS_SESSION_OPENED = NOTIF_MSG_FOCUS_SESSION_OPENED;
module.exports.NOTIF_MSG_FOCUS_SESSION_COMPLETED = NOTIF_MSG_FOCUS_SESSION_COMPLETED;
module.exports.NOTIF_MSG_FOCUS_SESSION_FEEDBACK = NOTIF_MSG_FOCUS_SESSION_FEEDBACK;
module.exports.NOTIF_TYPE_FOCUS_SESSION_APPROACH = NOTIF_TYPE_FOCUS_SESSION_APPROACH;
module.exports.NOTIF_MSG_FOCUS_SESSION_APPROACH = NOTIF_MSG_FOCUS_SESSION_APPROACH;